seq_length: 24
feature_size: 5
results_folder: 
num_samples: 1000
stressed_features: [0, 1]
stressed_seq_indices: [0, 1, 2, 3, 4, 5, 6]
data_hist_path: # .csv
data_stress_path: # .csv 
milestone: null
data_root:  # .csv