model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 24
    feature_size: 11
    n_layer_enc: 3
    n_layer_dec: 3
    d_model: 96  # increased for 11 features
    timesteps: 250
    sampling_timesteps: 250
    loss_type: 'l2'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 5.0e-5
  max_epochs: 10
  results_folder: #
  gradient_accumulate_every: 4
  save_cycle: 2  # save every 2 epochs
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: Diffusion_TS
      proportion: 1.0  # Set to rate < 1 if training conditional generation
      data_root: #
      window: 24  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: Diffusion_TS
      proportion: 0.9  # rate
      data_root: #
      window: 24  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 100
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 32
  sample_size: 128
  shuffle: True